%YAML 1.2
---
name: One dark
parent-scheme: Darcula
colors:
  ADDED_LINES_COLOR: 98c379
  CARET_COLOR: 528bff
  CARET_ROW_COLOR: 2c313c
  CONSOLE_BACKGROUND_KEY: 282c34
  DELETED_LINES_COLOR: e06c75
  ERROR_HINT: '781732'
  FOLDED_TEXT_BORDER_COLOR: ''
  GUTTER_BACKGROUND: 282c34
  INDENT_GUIDE: 3b4048
  LINE_NUMBER_ON_CARET_ROW_COLOR: '737984'
  LINE_NUMBERS_COLOR: '495162'
  METHOD_SEPARATORS_COLOR: 3b4048
  MODIFIED_LINES_COLOR: d19a66
  QUESTION_HINT: 376c89
  RIGHT_MARGIN_COLOR: '606368'
  SELECTED_INDENT_GUIDE: '606368'
  SELECTED_TEARLINE_COLOR: 6b6e73
  SELECTION_BACKGROUND: 3e4350
  SEPARATOR_BELOW_COLOR: ''
  TEARLINE_COLOR: 4f575f
  TOOLTIP: ''
  VISUAL_INDENT_GUIDE: 3b4048
  WHITESPACES: 4b575f
inheriting-attributes:
  ANNOTATION_NAME_ATTRIBUTES: DEFAULT_METADATA
  CUSTOM_KEYWORD1_ATTRIBUTES: DEFAULT_KEYWORD
  CUSTOM_STRING_ATTRIBUTES: DEFAULT_STRING
  CUSTOM_VALID_STRING_ESCAPE_ATTRIBUTES: DEFAULT_VALID_STRING_ESCAPE
  DEFAULT_IDENTIFIER: TEXT
  DEFAULT_REASSIGNED_LOCAL_VARIABLE: DEFAULT_LOCAL_VARIABLE
  DEFAULT_REASSIGNED_PARAMETER: DEFAULT_PARAMETER
  DEFAULT_STATIC_METHOD: DEFAULT_FUNCTION_DECLARATION
  DEFAULT_TEMPLATE_LANGUAGE_COLOR: TEXT
  JAVA_KEYWORD: DEFAULT_KEYWORD
  JAVA_VALID_STRING_ESCAPE: DEFAULT_VALID_STRING_ESCAPE
  KOTLIN_ANNOTATION: ANNOTATION_NAME_ATTRIBUTES
  XML_ATTRIBUTE_NAME: DEFAULT_ATTRIBUTE
attributes:
  ANGLE_BRACKETS_RAINBOW_COLOR0: ffd700
  ANGLE_BRACKETS_RAINBOW_COLOR1: da70d6
  ANGLE_BRACKETS_RAINBOW_COLOR2: 87cefa
  ANGLE_BRACKETS_RAINBOW_COLOR3: ffd700
  ANGLE_BRACKETS_RAINBOW_COLOR4: da70d6
  ANNOTATION_ATTRIBUTE_NAME_ATTRIBUTES: d19a66
  APACHE_CONFIG.ARG_LEXEM: 98c379
  APACHE_CONFIG.COMMENT:
    foreground: 59626f
    italic: theme
  APACHE_CONFIG.IDENTIFIER: c679dd
  BAD_CHARACTER:
    background: 9b3636
  BOOKMARKS_ATTRIBUTES: {}
  BREADCRUMBS_CURRENT:
    foreground: abb2bf
    background: 353a46
  BREADCRUMBS_DEFAULT: abb2bf
  BREADCRUMBS_HOVERED:
    foreground: abb2bf
    background: 444b5a
  BREADCRUMBS_INACTIVE: abb2bf
  BREAKPOINT_ATTRIBUTES:
    background: 743d3d
  BUILDOUT.KEY: c679dd
  BUILDOUT.KEY_VALUE_SEPARATOR: a6b2c0
  BUILDOUT.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  BUILDOUT.SECTION_NAME: d2945d
  BUILDOUT.VALUE: 98c379
  CLASS_REFERENCE: e5c17c
  Clojure Atom: c679dd
  Clojure Character: 98c379
  Clojure Keyword: df6a73
  Clojure Line comment:
    foreground: 59626f
    italic: theme
  Clojure Literal:
    foreground: fda5ff
    bold: always
  Clojure Numbers: d2945d
  Clojure Strings: 98c379
  COFFEESCRIPT.BAD_CHARACTER:
    background: 6e3b3b
  COFFEESCRIPT.BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  COFFEESCRIPT.BOOLEAN: d2945d
  COFFEESCRIPT.CLASS_NAME: e5c17c
  COFFEESCRIPT.COLON: ffffff
  COFFEESCRIPT.ESCAPE_SEQUENCE: 57b6c2
  COFFEESCRIPT.EXISTENTIAL: a6b2c0
  COFFEESCRIPT.EXPRESSIONS_SUBSTITUTION_MARK: be4f44
  COFFEESCRIPT.FUNCTION: c679dd
  COFFEESCRIPT.FUNCTION_BINDING: c679dd
  COFFEESCRIPT.FUNCTION_NAME: 61afef
  COFFEESCRIPT.GLOBAL_VARIABLE: e06c75
  COFFEESCRIPT.HEREDOC_CONTENT: 98c379
  COFFEESCRIPT.HEREDOC_ID: 98c379
  COFFEESCRIPT.HEREGEX_CONTENT: d19a66
  COFFEESCRIPT.HEREGEX_ID: 57b6c2
  COFFEESCRIPT.JAVASCRIPT_CONTENT: c678dd
  COFFEESCRIPT.JAVASCRIPT_ID: 98c379
  COFFEESCRIPT.KEYWORD: c679dd
  COFFEESCRIPT.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  COFFEESCRIPT.NUMBER: d2945d
  COFFEESCRIPT.OBJECT_KEY: df6a73
  COFFEESCRIPT.OPERATIONS: a6b2c0
  COFFEESCRIPT.PROTOTYPE: 61afef
  COFFEESCRIPT.REGULAR_EXPRESSION_CONTENT: 57b6c2
  COFFEESCRIPT.REGULAR_EXPRESSION_FLAG: 57b6c2
  COFFEESCRIPT.REGULAR_EXPRESSION_ID: 57b6c2
  COFFEESCRIPT.STRING: 98c379
  COFFEESCRIPT.STRING_LITERAL: 98c379
  COFFEESCRIPT.THIS: df6a73
  CONDITIONALLY_NOT_COMPILED:
    foreground: 59626f
    italic: theme
  CONSOLE_BLUE_BRIGHT_OUTPUT:
    foreground: 61afef
    bold: always
  CONSOLE_BLUE_OUTPUT: 61afef
  CONSOLE_CYAN_BRIGHT_OUTPUT:
    foreground: 56b6c2
    bold: always
  CONSOLE_CYAN_OUTPUT: 56b6c2
  CONSOLE_ERROR_OUTPUT: be5046
  CONSOLE_GRAY_OUTPUT: '828997'
  CONSOLE_GREEN_BRIGHT_OUTPUT:
    foreground: 98c379
    bold: always
  CONSOLE_GREEN_OUTPUT: 98c379
  CONSOLE_MAGENTA_BRIGHT_OUTPUT:
    foreground: c678dd
    bold: always
  CONSOLE_MAGENTA_OUTPUT: c678dd
  CONSOLE_NORMAL_OUTPUT: abb2bf
  CONSOLE_RED_BRIGHT_OUTPUT:
    foreground: e06c75
    bold: always
  CONSOLE_RED_OUTPUT: e06c75
  CONSOLE_SYSTEM_OUTPUT: e4e4ff
  CONSOLE_USER_INPUT:
    foreground: 6ae96a
    italic: theme
  CONSOLE_WHITE_OUTPUT: abb2bf
  CONSOLE_YELLOW_BRIGHT_OUTPUT:
    foreground: d19a66
    bold: always
  CONSOLE_YELLOW_OUTPUT: d19a66
  CONSTRUCTOR_CALL_ATTRIBUTES: e5c07b
  CSS.COLON: '828997'
  CSS.COLOR: 50b6c3
  CSS.COMMENT:
    foreground: 59626f
    italic: theme
  CSS.FUNCTION: 57b6c2
  CSS.HASH: 50b6c3
  CSS.IDENT: d39a63
  CSS.IMPORTANT: c676df
  CSS.KEYWORD: c678dd
  CSS.NUMBER: d2945d
  CSS.OPERATORS: c676df
  CSS.PROPERTY_NAME: abb2bf
  CSS.PROPERTY_VALUE: d39a63
  CSS.PSEUDO: d39a63
  CSS.STRING: 98c379
  CSS.TAG_NAME: df6a73
  CSS.UNICODE.RANGE: d39a63
  CSS.URL: abb2bf
  CTRL_CLICKABLE:
    foreground: 61afef
    effect_color: 61afef
    underscored: always
  CUSTOM_KEYWORD2_ATTRIBUTES: fda5ff
  CUSTOM_KEYWORD3_ATTRIBUTES: 71d7d7
  CUSTOM_KEYWORD4_ATTRIBUTES: ffc2c2
  DEFAULT_ATTRIBUTE: d19a66
  DEFAULT_BLOCK_COMMENT:
    foreground: 5c6370
    italic: theme
  DEFAULT_CLASS_NAME: e5c07b
  DEFAULT_COMMA: {}
  DEFAULT_CONSTANT: 56b6c2
  DEFAULT_DOC_COMMENT:
    foreground: 5c6370
    italic: theme
  DEFAULT_DOC_COMMENT_TAG: c678dd
  DEFAULT_DOC_COMMENT_TAG_VALUE: d19a66
  DEFAULT_ENTITY: e06c75
  DEFAULT_FUNCTION_CALL: 61afef
  DEFAULT_FUNCTION_DECLARATION: 61afef
  DEFAULT_INSTANCE_FIELD: e06c75
  DEFAULT_INTERFACE_NAME: ffc66d
  DEFAULT_INVALID_STRING_ESCAPE:
    foreground: 56b6c2
    effect_color: f44747
    underwaved: always
  DEFAULT_KEYWORD:
    foreground: c678dd
    italic: theme
  DEFAULT_LINE_COMMENT:
    foreground: 5c6370
    italic: theme
  DEFAULT_METADATA:
    foreground: e5c07b
    italic: theme
  DEFAULT_NUMBER: d19a66
  DEFAULT_PARAMETER: d19a66
  DEFAULT_SEMICOLON: {}
  DEFAULT_STATIC_FIELD: e06c75
  DEFAULT_STRING: 98c379
  DEFAULT_VALID_STRING_ESCAPE: 56b6c2
  DELETED_TEXT_ATTRIBUTES:
    background: '692424'
  DEPRECATED_ATTRIBUTES:
    effect_color: abb2bf
    strikeout: always
  DIFF_CONFLICT:
    background: 763f34
    error_stripe_color: ff6647
  DIFF_DELETED:
    background: 5b5b5b
    error_stripe_color: '747474'
  DIFF_INSERTED:
    background: 2f632f
    error_stripe_color: 99ff99
  DIFF_MODIFIED:
    background: '465983'
    error_stripe_color: 99ccff
  DJANGO_COMMENT:
    foreground: 59626f
    italic: theme
  DJANGO_FILTER: 57b6c2
  DJANGO_ID: d2945d
  DJANGO_KEYWORD: c679dd
  DJANGO_NUMBER: d2945d
  DJANGO_STRING_LITERAL: 98c379
  DJANGO_TAG_NAME: c676df
  DUPLICATE_FROM_SERVER: {}
  ENUM_CONST: 98c379
  ERRORS_ATTRIBUTES:
    effect_color: f44747
    error_stripe_color: f44747
    underwaved: always
  EXECUTIONPOINT_ATTRIBUTES:
    foreground: '101'
    background: c7c7ff
  FIRST SYMBOL IN LIST:
    foreground: df6a73
    bold: always
  FOLDED_TEXT_ATTRIBUTES:
    foreground: 878e9b
    background: '313741'
    underwaved: always
  FOLLOWED_HYPERLINK_ATTRIBUTES:
    foreground: c678dd
    effect_color: c678dd
    underscored: always
  GENERIC_SERVER_ERROR_OR_WARNING:
    effect_color: ff8c00
    error_stripe_color: ff8c00
    underwaved: always
  GHERKIN_COMMENT:
    foreground: 59626f
    italic: theme
  GHERKIN_KEYWORD: c679dd
  GHERKIN_OUTLINE_PARAMETER_SUBSTITUTION: df6a73
  GHERKIN_PYSTRING: 98c379
  GHERKIN_REGEXP_PARAMETER: 98c379
  GHERKIN_TABLE_HEADER_CELL: df6a73
  GHERKIN_TABLE_PIPE: c679dd
  GHERKIN_TAG: c679dd
  GO_BRACES: aeb6c0
  GO_BRACKET: aeb6c0
  GO_BUILTIN_CONSTANT:
    foreground: d2945d
    italic: theme
  GO_BUILTIN_FUNCTION: 57b6c2
  GO_BUILTIN_FUNCTION_CALL: 57b6c2
  GO_BUILTIN_TYPE: c679dd
  GO_BUILTIN_TYPE_REFERENCE: c679dd
  GO_BUILTIN_VARIABLE: d2945d
  GO_COMMA: aeb6c0
  GO_EXPORTED_FUNCTION:
    foreground: 61afef
    italic: theme
  GO_EXPORTED_FUNCTION_CALL: 57b6c2
  GO_KEYWORD: c679dd
  GO_LOCAL_CONSTANT:
    foreground: e06c75
    italic: theme
  GO_LOCAL_FUNCTION: 61afef
  GO_LOCAL_FUNCTION_CALL: 57b6c2
  GO_LOCAL_VARIABLE_CALL: 57b6c2
  GO_METHOD_RECEIVER: aeb6c0
  GO_NUMBER: d2945d
  GO_OPERATOR: c679dd
  GO_PACKAGE_EXPORTED_CONSTANT:
    foreground: e06c75
    italic: theme
  GO_PACKAGE_EXPORTED_VARIABLE_CALL: 57b6c2
  GO_PACKAGE_LOCAL_CONSTANT:
    foreground: e06c75
    italic: theme
  GO_PACKAGE_LOCAL_VARIABLE_CALL: 57b6c2
  GO_SCOPE_VARIABLE: aeb6c0
  GO_SEMICOLON: aeb6c0
  GO_STRING: 98c379
  GO_STRUCT_EXPORTED_MEMBER_CALL: 57b6c2
  GO_STRUCT_LOCAL_MEMBER_CALL: 57b6c2
  GO_TYPE_REFERENCE: aeb6c0
  GQL_ID: d2945d
  GQL_INT_LITERAL: d2945d
  GQL_KEYWORD: c679dd
  GQL_STRING_LITERAL: 98c379
  HAML_CLASS: df6a73
  HAML_COMMENT:
    foreground: 59626f
    italic: theme
  HAML_ID: df6a73
  HAML_STRING: 98c379
  HAML_STRING_INTERPOLATED: 98c379
  HAML_TAG_NAME: df6a73
  HTML_ATTRIBUTE_NAME: d2945d
  HTML_ATTRIBUTE_VALUE: 98c379
  HTML_COMMENT:
    foreground: 59626f
    italic: theme
  HTML_ENTITY_REFERENCE: d2945d
  HTML_TAG_NAME: e26b73
  HYPERLINK_ATTRIBUTES:
    foreground: c678dd
    effect_color: c678dd
    underscored: always
  IDENTIFIER_UNDER_CARET_ATTRIBUTES:
    background: 484e5b
  IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES: {}
  INACTIVE_HYPERLINK_ATTRIBUTES:
    effect_color: abb2bf
    underscored: always
  INFO_ATTRIBUTES:
    effect_color: e5c07b
    error_stripe_color: e5c07b
    underwaved: always
  INJECTED_LANGUAGE_FRAGMENT: {}
  INLINE_PARAMETER_HINT:
    foreground: abb2bf
    background: 5c6370
  INLINE_PARAMETER_HINT_CURRENT:
    foreground: abb2bf
    background: 48709b
  INLINE_PARAMETER_HINT_HIGHLIGHTED:
    foreground: abb2bf
    background: '414855'
  IVAR: df6a73
  JAVA_STRING: 98c379
  JS.ATTRIBUTE:
    background: '423535'
  JS.BADCHARACTER:
    background: 6e3b3b
  JS.BLOCK_COMEMNT:
    foreground: 59626f
    italic: theme
  JS.DOC_MARKUP:
    background: 223f22
  JS.DOC_TAG:
    foreground: c676df
    bold: always
  JS.GLOBAL_FUNCTION: 5aaef1
  JS.GLOBAL_VARIABLE: abb2bf
  JS.INSTANCE_MEMBER_VARIABLE: abb2bf
  JS.INVALID_STRING_ESCAPE:
    foreground: 68e868
    background: '481515'
  JS.LOCAL_VARIABLE: abb2bf
  JS.NUMBER: d2945d
  JS.OPERATION_SIGN: a6b2c0
  JS.REGEXP: 57b6c2
  JS.STATIC_MEMBER_FUNCTION:
    italic: theme
  JS.STATIC_MEMBER_VARIABLE:
    foreground: fda5ff
    bold: always
    italic: theme
  JS.STRING: 98c379
  JS.VALID_STRING_ESCAPE: 57b6c2
  JSON.KEYWORD: 5aaef1
  JSON.PROPERTY_KEY: e06c75
  JSON.STRING: 98c476
  LABEL: c679dd
  LESS_ID_SELECTOR: 61afef
  LESS_OPERATORS: abb2bf
  LESS_TAG_NAME: c678dd
  LESS_VARIABLE: df6a73
  LIVE_TEMPLATE_ATTRIBUTES:
    effect_color: f44747
  LOCALE.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  LOCALE.MSGCTXT_KEYWORD: c679dd
  LOCALE.MSGID_KEYWORD: c679dd
  LOCALE.MSGID_PLURAL_KEYWORD: c679dd
  LOCALE.MSGSTR_KEYWORD: c679dd
  LOCALE.MSGSTR_PLURAL_KEYWORD: c679dd
  LOCALE.STRING_LITERAL: 98c379
  LOG_WARNING_OUTPUT: e5c07b
  MACRONAME: 61afef
  MARKED_FOR_REMOVAL_ATTRIBUTES:
    effect_color: f44747
    strikeout: always
  MATCHED_BRACE_ATTRIBUTES:
    background: 515a6b
  MESSAGE_ARGUMENT: 61afef
  NOT_USED_ELEMENT_ATTRIBUTES: 7d8491
  OC_FORMAT_TOKEN: 98c379
  OC.BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  OC.CPP_KEYWORD: c679dd
  OC.DIRECTIVE: c679dd
  OC.EXTERN_VARIABLE: df6a73
  OC.FUNCTION: 61afef
  OC.GLOBAL_VARIABLE: df6a73
  OC.KEYWORD: c679dd
  OC.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  OC.LOCAL_VARIABLE: df6a73
  OC.NUMBER: d2945d
  OC.PARAMETER: a6b2c0
  OC.PROPERTY: df6a73
  OC.SELFSUPERTHIS: df6a73
  OC.STRING: 98c379
  OC.STRUCT_FIELD: 98c379
  PHP_BAD_CHARACTER:
    background: 6e3b3b
  PHP_COMMENT:
    foreground: 59626f
    italic: theme
  PHP_CONSTANT: d2945d
  PHP_DOC_COMMENT_ID:
    foreground: 59626f
    italic: theme
  PHP_DOC_TAG:
    bold: always
  PHP_ESCAPE_SEQUENCE: 57b6c2
  PHP_EXEC_COMMAND_ID: 98c379
  PHP_HEREDOC_CONTENT: 98c379
  PHP_HEREDOC_ID:
    bold: always
  PHP_KEYWORD: c679dd
  PHP_MARKUP_ID:
    background: 223f22
  PHP_NUMBER: d2945d
  PHP_OPERATION_SIGN: a6b2c0
  PHP_SCRIPTING_BACKGROUND:
    background: 2a2d32
  PHP_STRING: 98c379
  PHP_TAG: c679dd
  PHP_VAR: c679dd
  PROTOCOL_REFERENCE: e5c17c
  PUPPET_BAD_CHARACTER:
    background: 6e3b3b
  PUPPET_BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  PUPPET_CLASS: e5c17c
  PUPPET_ESCAPE_SEQUENCE: 57b6c2
  PUPPET_KEYWORD: c679dd
  PUPPET_NUMBER: d2945d
  PUPPET_OPERATION_SIGN: a6b2c0
  PUPPET_REGEX: 57b6c2
  PUPPET_SQ_STRING: 98c379
  PUPPET_STRING: 98c379
  PUPPET_VARIABLE_INTERPOLATION: 98c379
  PY.BUILTIN_NAME: 57b6c2
  PY.CLASS_DEFINITION: e5c17c
  PY.DECORATOR: 61afef
  PY.DOC_COMMENT: 98c476
  PY.FUNC_DEFINITION: 61afef
  PY.INVALID_STRING_ESCAPE:
    foreground: 68e868
    background: '481515'
  PY.KEYWORD: c679dd
  PY.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  PY.NUMBER: d2945d
  PY.PARAMETER: d19a66
  PY.PREDEFINED_USAGE: e06c75
  PY.SELF_PARAMETER: e06c75
  PY.STRING: 98c379
  PY.VALID_STRING_ESCAPE: 57b6c2
  REGEXP.BAD_CHARACTER:
    background: 6e3b3b
  REGEXP.CHAR_CLASS: 57b6c2
  REGEXP.COMMENT:
    foreground: 59626f
    italic: theme
  REGEXP.ESC_CHARACTER: 57b6c2
  REGEXP.INVALID_STRING_ESCAPE:
    foreground: 68e868
    background: '481515'
  REGEXP.META: c679dd
  REGEXP.QUOTE_CHARACTER: 57b6c2
  REGEXP.REDUNDANT_ESCAPE: 57b6c2
  REST.EXPLICIT: c679dd
  REST.FIELD: c679dd
  REST.FIXED:
    background: 48485f
  REST.INLINE:
    background: '273627'
  REST.INTERPRETED:
    background: 4d5d3d
  REST.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  REST.REF.NAME: 98c379
  REST.SECTION.HEADER: d2945d
  RHTML_COMMENT_ID:
    foreground: 59626f
    italic: theme
  RHTML_EXPRESSION_END_ID: be4f44
  RHTML_EXPRESSION_START_ID: be4f44
  RHTML_OMIT_NEW_LINE_ID: be4f44
  RHTML_SCRIPTLET_END_ID: be4f44
  RHTML_SCRIPTLET_START_ID: be4f44
  ROUND_BRACKETS_RAINBOW_COLOR0: ffd700
  ROUND_BRACKETS_RAINBOW_COLOR1: da70d6
  ROUND_BRACKETS_RAINBOW_COLOR2: 87cefa
  ROUND_BRACKETS_RAINBOW_COLOR3: ffd700
  ROUND_BRACKETS_RAINBOW_COLOR4: da70d6
  RUBY_COMMENT:
    foreground: 5c6370
    italic: theme
  RUBY_CONSTANT: d2945d
  RUBY_CONSTANT_DECLARATION: d19a66
  RUBY_CVAR: df6a73
  RUBY_ESCAPE_SEQUENCE: 57b6c2
  RUBY_EXPR_IN_STRING: be5046
  RUBY_GVAR: df6a73
  RUBY_HASH_ASSOC: a6b2c0
  RUBY_HEREDOC_CONTENT: 98c379
  RUBY_HEREDOC_ID: 98c379
  RUBY_INTERPOLATED_STRING: 98c379
  RUBY_INVALID_ESCAPE_SEQUENCE:
    foreground: 68e868
    background: '481515'
  RUBY_IVAR: df6a73
  RUBY_KEYWORD: c678dd
  RUBY_LINE_CONTINUATION: a6b2c0
  RUBY_LOCAL_VAR_ID: abb2bf
  RUBY_METHOD_NAME: 61afef
  RUBY_NTH_REF: e06c75
  RUBY_NUMBER: d2945d
  RUBY_OPERATION_SIGN: a6b2c0
  RUBY_PARAMDEF_CALL: abb2bf
  RUBY_PARAMETER_ID: abb2bf
  RUBY_REGEXP: 57b6c2
  RUBY_SPECIFIC_CALL: 61afef
  RUBY_STRING: 98c379
  RUBY_SYMBOL: 56b6c2
  RUBY_WORDS: 98c379
  RUNTIME_ERROR:
    effect_color: ff8c00
    error_stripe_color: f44747
    dotted-line: always
  SASS_COMMENT:
    foreground: 59626f
    italic: theme
  SASS_DEFAULT: c679dd
  SASS_EXTEND: c679dd
  SASS_FUNCTION: 57b6c2
  SASS_IDENTIFIER: d2945d
  SASS_IMPORTANT: c679dd
  SASS_KEYWORD: c679dd
  SASS_MIXIN: d2945d
  SASS_NUMBER: d2945d
  SASS_PROPERTY_NAME: d2945d
  SASS_PROPERTY_VALUE: 68e868
  SASS_STRING: 98c379
  SASS_TAG_NAME: c679dd
  SASS_URL: df6a73
  SASS_VARIABLE: df6a73
  SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
  SLIM_BAD_CHARACTER:
    foreground: 272b33
    background: f2777a
  SLIM_CLASS: df6a73
  SLIM_COMMENT:
    foreground: 59626f
    italic: theme
  SLIM_DOCTYPE_KWD: df6a73
  SLIM_FILTER: df6a73
  SLIM_ID: df6a73
  SLIM_INTERPOLATION: 98c379
  SLIM_STRING_INTERPOLATED: 98c379
  SLIM_TAG: df6a73
  SLIM_TAG_ATTR_KEY: d2945d
  SMARTY_BACKGROUND:
    background: 2a2d32
  SMARTY_BAD_CHARACTER:
    background: 6e3b3b
  SMARTY_COMMENT:
    foreground: 59626f
    italic: theme
  SMARTY_KEYWORD: c679dd
  SMARTY_NUMBER: d2945d
  SMARTY_OPERATION_SIGN: a6b2c0
  SMARTY_STRING: 98c379
  SQL_BAD_CHARACTER:
    background: 6e3b3b
  SQL_COLUMN: abb2bf
  SQL_COMMENT:
    foreground: 59626f
    italic: theme
  SQL_KEYWORD: c679dd
  SQL_NUMBER: d2945d
  SQL_PROCEDURE:
    foreground: 61afef
    italic: theme
  SQL_SCHEMA: 61afef
  SQL_STRING: 98c379
  SQL_SYNTETIC_ENTITY: fda5ff
  SQL_TABLE: d19a66
  SQUARE_BRACKETS_RAINBOW_COLOR0: ffd700
  SQUARE_BRACKETS_RAINBOW_COLOR1: da70d6
  SQUARE_BRACKETS_RAINBOW_COLOR2: 87cefa
  SQUIGGLY_BRACKETS_RAINBOW_COLOR0: ffd700
  SQUIGGLY_BRACKETS_RAINBOW_COLOR1: da70d6
  SQUIGGLY_BRACKETS_RAINBOW_COLOR2: 87cefa
  STATIC_METHOD_ATTRIBUTES: e5c07b
  STATIC_METHOD_IMPORTED_ATTRIBUTES: 61afef
  TAG_ATTR_KEY: d2945d
  TEMPLATE_VARIABLE_ATTRIBUTES: d19a66
  TEXT:
    foreground: abb2bf
    background: 282c34
  TEXT_SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
    error_stripe_color: 457dff
  TODO_DEFAULT_ATTRIBUTES:
    foreground: ff8c00
    italic: theme
  TS.CLASS: e5c07b
  TS.GLOBAL_FUNCTION: 56b6c2
  TS.INSTANCE_MEMBER_FUNCTION: 61afef
  TS.INSTANCE_MEMBER_VARIABLE: e06c75
  TS.INTERFACE: e5c07b
  TS.KEYWORD: c678dd
  TS.MODULE_NAME: e5c07b
  TS.STATIC_MEMBER_FUNCTION: 61afef
  TS.STATIC_MEMBER_VARIABLE: e06c75
  TWIG_BACKGROUND:
    background: 2a2d32
  TWIG_BAD_CHARACTER:
    background: 6e3b3b
  TWIG_COMMENT:
    foreground: 59626f
    italic: theme
  TWIG_KEYWORD: c679dd
  TWIG_NUMBER: d2945d
  TWIG_OPERATION_SIGN: a6b2c0
  TWIG_STRING: 98c379
  TYPEDEF: c679dd
  TYPE_PARAMETER_NAME_ATTRIBUTES: e5c07b
  TYPO:
    effect_color: 98c379
    underwaved: always
  UNMATCHED_BRACE_ATTRIBUTES:
    background: '583535'
  WARNING_ATTRIBUTES:
    effect_color: ff8c00
    error_stripe_color: ff8c00
    underwaved: always
  WRITE_IDENTIFIER_UNDER_CARET_ATTRIBUTES:
    background: 484e5b
  WRITE_SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
  WRONG_REFERENCES_ATTRIBUTES: f44747
  XML_ATTRIBUTE_VALUE: 98c379
  XML_COMMENT:
    foreground: 59626f
    italic: theme
  XML_ENTITY_REFERENCE: d2945d
  XML_NS_PREFIX: d2945d
  XML_PROLOGUE:
    italic: theme
  XML_TAG_NAME:
    foreground: e06c75
    bold: always
  YAML_COMMENT:
    foreground: 59626f
    italic: theme
  YAML_SCALAR_DSTRING: 98c379
  YAML_SCALAR_KEY: df6a73
  YAML_SCALAR_LIST: 98c379
  YAML_SCALAR_STRING: 98c379
  YAML_SCALAR_VALUE: 98c379
  YAML_SIGN: 98c476
  YAML_TEXT:
    foreground: 98c379
