remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
search_enabled: true
ga_tracking: UA-145408326-1
title: JetBrains One Dark
description: One dark color scheme for JetBrains IDEs
aux_links:
  'JetBrains One Dark on GitHub':
    - //github.com/markypython/jetbrains-one-dark-theme
source: pages
include:
  - index.md
  - installation.md
  - configuration.md
  - development.md
  - publishing.md
  - screenshots.md
  - updating-to-v2.md

theme: jekyll-theme-cayman